### ISSUE TITLE
VS2017 Pro crashes when opening solution if PPT 2017 is enabled 

### ISSUE THREAD

**Issue by tkberg** [Microsoft/VS-PPT#104]
VS 2017 Pro is installed on **E: (not the OS drive C:)** and opening a solution with PPT 2017 enabled crashes VS 2017. If solution is opened with PPT 2017 disabled it opens without a crash.

Description
Faulting Application Path:	E:\Visual Studio 2017\Common7\IDE\devenv.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	devenv.exe
Problem Signature 02:	15.0.26228.4
Problem Signature 03:	58bb453b
Problem Signature 04:	mscorlib
Problem Signature 05:	4.6.1055.0
Problem Signature 06:	563c0eac
Problem Signature 07:	5b41
Problem Signature 08:	b
Problem Signature 09:	StreamJsonRpc.RemoteInvocation
OS Version:	6.1.7601.2.1.0.256.4
Locale ID:	2077
Additional Information 1:	6d74
Additional Information 2:	6d74ccbfc46b25da03669ccd9d26ab12
Additional Information 3:	e8df
Additional Information 4:	e8df6f6243fd976099b569ddb0f9bd0a

**Comment by tokotech** [comment]
I have the same problem

**Comment by roeba** [comment]
Same for me. This makes the whole extension useless. Does anyone from MS need more info on this to fix it?

**Comment by phillijw** [comment]
Try disabling "Power Commands". It solved this issue for me.

**Comment by justcla** [comment]
Instead of disabling, update all PPT extensions. Then the fix will be brought down.

**Comment by phillijw** [comment]
@justcla Then why is mine still broken? Can you say what version the fix is so I can ensure I have or don't have it?

**Comment by justcla** [comment]
The fix was implemented in every PPT extension.
Each one went up one version.
For PowerCommands, the fix was in version 15.0.3

The best path to success is to uninstall all PPT extensions, plus the installer. Then delete the .productivitypowerpack2017 file from the user directory.
Restart VS.
Then install PPT fresh. It will bring down all the latest extensions, which should fix the problem.

**Comment by justcla** [comment]
Message above was in relation to Issue #120.

If the issue you are having is related to errors occurring when VS is installed on a drive other than C:\, that could be a different issue.

**Comment by phillijw** [comment]
I set all PPT extensions to auto update (even if they were disabled). I then enabled/disabled/enabled Power Commands. I then closed VS and opened it. Now the problem appears to be fixed.

There are a few extensions at version 15.0.2, some at 15.0.3, and a couple at 15.0.4 but some are releasing release notes for the latest versions so I'm not sure which one was the actual fix for this issue.

**Comment by justcla** [comment]
Each of the extensions have their own version numbers.
The fix was in all the extensions. If any of the extensions are out of date, you're likely to see errors about TelemetryDLL.

**Comment by roeba** [comment]
Updating the extensions and Un/Reinstalling them did not help, the error is still there. Disabling Power Commands brought no improvement.

The crash happens after VS has loaded the solution completely (the project is not in the initializing stage any more, but finished) and displays all the files etc. in it.

When I got the crash window, I clicked on the debug button and opened the debugging session in my VS2012. In there, I got the exception details:

```
System.ExecutionEngineException

Request locate failed with message: Cannot find service module info file '*/remoteHostService.servicehub.service.json' in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\ServiceHub\Services', using discovery services failed: VsixServiceDiscovery: ExternalSettingsManager::GetScopePaths failed to initialize PkgDefManager for C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
   bei Microsoft.VisualStudio.Settings.ExternalSettingsManager.GetScopePaths(String applicationPath, String suffixOrName, String vsVersion, Boolean isLogged, Boolean isForIsolatedApplication)
   bei Microsoft.VisualStudio.Settings.ExternalSettingsManager.CreateForApplication(String applicationPath, IInteropLogger logger)
   bei Microsoft.ServiceHub.VsixServiceDiscovery.DiscoveryService.EnumerateContentLocations()
   bei Microsoft.ServiceHub.VsixServiceDiscovery.DiscoveryService.EnsureServiceModulesEnumerated()
   bei Microsoft.ServiceHub.VsixServiceDiscovery.DiscoveryService.discoverService(String serviceName)
```

**Comment by justcla** [comment]
Thanks for the error report @roeba.
Sounds like an issue with trying to access ServiceHib on C:\
I'll look into it.

**Comment by AlexEyler** [comment]
@roeba does the crash occur without the PPT extension installed? It sounds like a different issue related to cache locking that some folks on the VS team are addressing in a future update.

**Comment by roeba** [comment]
@AlexEyler I uninstalled the PPT extension, but the crash still happens.

**Comment by justcla** [comment]
@roeba So you can confirm this is not an issue related to PPT?

**Comment by roeba** [comment]
@justcla Well the problem only appeared after installing PPT and with it the various extensions. If I deinstall all the extensions, too, it works and doesn't crash anymore. So it seems to be related to PPT.

**Comment by justcla** [comment]
Thanks @roeba 
Sounds like an issue with PPT not fully uninstalling correctly (and/or updating correctly).
I have seen issues with that where some extensions are left behind - often in a disabled state.
Completely uninstalling the old extensions will help remove that problem.

I've uploaded new extensions that don't include the Telemetry DLL, which was the cause of these problems. There should be no more issues now. Please let me know if you have success with the new extensions. Thanks

**Comment by roeba** [comment]
@justcla I tested the updated versions and after loading multiple VS solutions, restarting the PC and other things it never crashed once with all extensions enabled! So it seems to be fixed, thanks!

**Comment by justcla** [comment]
@roeba Woohoo!! Great success! :-D
